### PR TITLE
Allow a way to configure v4l camera input format

### PR DESCRIPTION
**Pull request by mar-kolya**
Add a RS_USBCAM_INPUT_FORMAT env variable to allow configuration of
v4l camera input format. This is useful when using RPI camera
via v4l because it allows one to use RPI's hardware encoder for h264.

### CODE REVIEW

**Comment by FilipStadler** [comment]
Yes som way to preload the USB - some USB caputure cards sometimes needs usb reset.
Also capture card like Elgato Camlink can 4K report wrong info colorspace bug example found here:

Solution found here https://github.com/xkahn/camlink but it would be nice to have the option i restreamer

**Comment by jstabenow** [comment]
@ioppermann Please have a look at this

**Comment by ioppermann** [comment]
This is now available in version 2.0.0, but currently only in the `datarhei/restreame:rpi-latest` image. Add a camera in the advanced setup. Choose the hardware device. Below is a drop-down where you can select a predefined input format or enter a custom one.

https://docs.datarhei.com/restreamer/knowledge-base/manual/edit-livestream/sources/video-settings (follow the numbers 1 -> 3 -> 2)

**Comment by sfahadshahzad** [comment]
does this patch will work with PCIE video capture cards as well like blackmagic decklink ?

Fahad

**Comment by ioppermann** [comment]
This pull request is for the old version of Restreamer. The latest version (2.0.0) supports setting an input format for v4l devices.

@sfahadshahzad If your capture devices are accessible via v4l (video4linux), then it will work. Please use the latest version of Restreamer.

**Comment by sfahadshahzad** [comment]
V4l doesn't support blackmagic devices.

Fahad

**Pull request closed without merging**
