### PR TITLE
Feature/add multiple outputs

### PR DESCRIPTION
**Pull request by wdalmijn**
### Summary
Refactored the way optional outputs work a bit so we can support multiple outputs.

### Description
In order to support multiple outputs, I did some changes to the code to allow for multiple optional outputs. First of all we need to adjust the database to have the streams available. Basically I will do a check when the `RS_EXTRA_OUTPUTS` is set to more than 1 whether the amount of streams in the DB matches the RS_EXTRA_OUTPUTS value, if not we will display a warning message. In order to actually make these streams in the database we will have to clear the database and let the createDefaultDatabase mechanism with my changes to create the proper database schema.

Then when the server boots and you're logged into the webinterface, if the outputs are more than 1, I altered the layout a bit to allow for more labeled outputs, which all have their individual start-stop button. The UX/UI is not ideal, but I am not a designer so I am open for comments on how to improve this :-).

Also I would like to add some proper documentation on how to use this functionality, but I don't know how you guys manage the website wiki.. let me know in which format you'd like to have it and I'll also add this to this PR.

### CODE REVIEW

**Comment by ioppermann** [comment]
Thanks for this extension. I will review it in the next few days.

We are also working on a new UI for the Restreamer and a new backend which will include multiple outputs by default.

**Comment by wdalmijn** [comment]
@ioppermann so the new backend makes this extension redundant? Anyway let me know if I should resolve these conflicts in the branch.

Also I was wondering if you guys have any other ideas you need help with? I was maybe thinking of migrating the old angular 1.5 frontend to React if that's also working for you guys.

**Comment by ioppermann** [comment]
@wdalmijn Yes, the new backend will make the this extension redundant, unfortunately. I thought of accepting this pull request, but keeping your extension in an unsupported branch. So people can build their own Docker image if they want to try it out.

With the new backend comes also a new frontend, which is written in React. As soon as it is released you're welcome to contribute.

**Comment by wdalmijn** [comment]
@ioppermann Alright no worries.. let me know if you need some help with that before the release. Happy to contribute, add test coverage, etc.

**Comment by wdalmijn** [comment]
@ioppermann I updated the PR again, in case you still want to merge this before the next main release.

**Comment by danionescu2007** [comment]
Hi @wdalmijn

Could you please give some steps on how to get your modified restreamer?
Thank you.

**Comment by wdalmijn** [comment]
@danionescu2007 I uploaded a docker image here:
https://hub.docker.com/r/winbulk/restreamer

**Comment by danionescu2007** [comment]
Thank you, I do appreciate it.

**Comment by Nesslax** [comment]
is it possible to merge so we can use it ?

**Comment by Nesslax** [comment]
hello @wdalmijn  I coulnt run your program into my mac or Raspberry 
```
> Restreamer@0.6.8 start /restreamer
> node ./src/start

/restreamer/src/classes/Restreamer.js:351
<<<<<<< HEAD
^^

SyntaxError: Unexpected token '<<'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/restreamer/src/start.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Restreamer@0.6.8 start: `node ./src/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Restreamer@0.6.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-16T17_53_36_611Z-debug.log
```

@ioppermann  Any news about the merge ? or this new feature ?

**Comment by ioppermann** [comment]
@Nesslax As mentioned in an earlier comment, we are working on a new version of the restreamer that already has this feature included. This pull request has some substantial changes which will make the transition to the new version more difficult. The release will be hopefully soon 😇

**Comment by wdalmijn** [comment]
@Nesslax Seems some merge conflict got stuck in here when I was making my changes for this upstream PR.

I will not update this PR anymore until the new version is out as @ioppermann mentioned, you can find a docker image at
https://hub.docker.com/r/winbulk/restreamer

or clone my repository at
https://github.com/wdalmijn/restreamer

for the time being until this new version is out. Good luck!

**Comment by mackenly** [comment]
@wdalmijn Quick question, used your docker image and started it up however I can't tell how to use additional outputs. Is that something you had added to the UI in your docker or didn't get to? It is appearing the same as the regular restreamer.

Know you're not actively working on it since there's a new version in development that will make it obsolete, however, I wanted to jump in to see if I could try this out as is. Thanks!

**Comment by wdalmijn** [comment]
> @wdalmijn Quick question, used your docker image and started it up however I can't tell how to use additional outputs. Is that something you had added to the UI in your docker or didn't get to? It is appearing the same as the regular restreamer.
> 
> Know you're not actively working on it since there's a new version in development that will make it obsolete, however, I wanted to jump in to see if I could try this out as is. Thanks!

You need to set `RS_EXTRA_OUTPUTS={numberOfOutputs}` in your environment section of the docker-compose file,, where `{numberOfOutputs}` is an integer value. This should then update the UI accordingly with more outputs. Remember to delete the database though in the `db` folder, as it needs to be rebuilt for this change to become active.

**Comment by mackenly** [comment]
@wdalmijn Thank you for the reply!

**Comment by jstabenow** [comment]
@wdalmijn 
Please excuse that we could not merge this.
The new version has a different architecture, so your Pull-Request was not compatible.

Thank you for your effort.

**Pull request closed without merging**
